# Generated by Django 2.0.5 on 2018-08-23 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0002_auto_20180823_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='', unique=True),
        ),
    ]
