# Generated by Django 2.0.5 on 2018-08-24 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0004_auto_20180824_0215'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='brand-slug', unique=True),
        ),
        migrations.AddField(
            model_name='categories',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='category-slug', unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='item-name', unique=True),
        ),
    ]
