# Generated by Django 2.0.5 on 2018-08-24 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0005_auto_20180824_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='slug',
        ),
    ]
