# Generated by Django 2.0.5 on 2018-08-27 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0012_auto_20180827_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='product',
            field=models.ForeignKey(default='null', on_delete='CASCADE', related_name='product', to='storeapp.Item'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='quantity',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
